<?php

use App\Tenant\Templates\Database\TemplateCatalogMigration;
use Illuminate\Database\Migrations\Migration;

return new class extends Migration
{
    public function up(): void
    {
        TemplateCatalogMigration::upsert('landing-page', $this->item());
    }

    public function down(): void
    {
        TemplateCatalogMigration::delete('landing-page', 'template-2');
    }

    /**
     * @return array<string, mixed>
     */
    private function item(): array
    {
        return [
            'key'           => 'template-2',
            'name'          => 'The Catalyst',
            'description'   => 'A sharp SaaS landing page with dashboard proof, metrics, feature cards, pricing, FAQ, and lead capture.',
            'preview_image' => '/template-assets/catalyst/preview.svg',
            'field_schema'  => [
                ['key' => 'business_name', 'label' => 'Brand Name', 'type' => 'text', 'required' => true],
                ['key' => 'nav_items', 'label' => 'Navigation Items', 'type' => 'repeater', 'fields' => [
                    ['key' => 'label', 'label' => 'Label', 'type' => 'text'],
                    ['key' => 'url', 'label' => 'URL', 'type' => 'text'],
                ]],
                ['key' => 'login_label', 'label' => 'Login Label', 'type' => 'text'],
                ['key' => 'login_url', 'label' => 'Login URL', 'type' => 'url'],
                ['key' => 'nav_cta_label', 'label' => 'Navigation CTA Label', 'type' => 'text'],
                ['key' => 'nav_cta_url', 'label' => 'Navigation CTA URL', 'type' => 'text'],
                ['key' => 'hero_badge', 'label' => 'Hero Badge', 'type' => 'text'],
                ['key' => 'hero_title', 'label' => 'Hero Title', 'type' => 'text', 'required' => true],
                ['key' => 'hero_accent_word', 'label' => 'Hero Accent Word', 'type' => 'text'],
                ['key' => 'hero_subtitle', 'label' => 'Hero Subtitle', 'type' => 'textarea'],
                ['key' => 'hero_primary_label', 'label' => 'Hero Primary Button Label', 'type' => 'text'],
                ['key' => 'hero_primary_url', 'label' => 'Hero Primary Button URL', 'type' => 'text'],
                ['key' => 'hero_secondary_label', 'label' => 'Hero Secondary Button Label', 'type' => 'text'],
                ['key' => 'hero_secondary_url', 'label' => 'Hero Secondary Button URL', 'type' => 'text'],
                ['key' => 'dashboard_tabs', 'label' => 'Dashboard Tabs', 'type' => 'repeater', 'fields' => [
                    ['key' => 'label', 'label' => 'Label', 'type' => 'text'],
                    ['key' => 'active', 'label' => 'Active Tab', 'type' => 'boolean'],
                ]],
                ['key' => 'dashboard_stats', 'label' => 'Dashboard Stat Cards', 'type' => 'repeater', 'fields' => [
                    ['key' => 'label', 'label' => 'Label', 'type' => 'text'],
                    ['key' => 'value', 'label' => 'Value', 'type' => 'text'],
                    ['key' => 'change', 'label' => 'Change', 'type' => 'text'],
                    ['key' => 'trend', 'label' => 'Trend', 'type' => 'select', 'options' => [
                        ['label' => 'Up', 'value' => 'up'],
                        ['label' => 'Down', 'value' => 'down'],
                    ]],
                ]],
                ['key' => 'dashboard_table_title', 'label' => 'Dashboard Table Title', 'type' => 'text'],
                ['key' => 'dashboard_filter_label', 'label' => 'Dashboard Filter Label', 'type' => 'text'],
                ['key' => 'dashboard_name_header', 'label' => 'Dashboard Name Header', 'type' => 'text'],
                ['key' => 'dashboard_events_header', 'label' => 'Dashboard Events Header', 'type' => 'text'],
                ['key' => 'dashboard_latency_header', 'label' => 'Dashboard Latency Header', 'type' => 'text'],
                ['key' => 'dashboard_uptime_header', 'label' => 'Dashboard Uptime Header', 'type' => 'text'],
                ['key' => 'dashboard_status_header', 'label' => 'Dashboard Status Header', 'type' => 'text'],
                ['key' => 'dashboard_rows', 'label' => 'Dashboard Rows', 'type' => 'repeater', 'fields' => [
                    ['key' => 'badge', 'label' => 'Badge', 'type' => 'text'],
                    ['key' => 'name', 'label' => 'Name', 'type' => 'text'],
                    ['key' => 'events', 'label' => 'Events', 'type' => 'text'],
                    ['key' => 'latency', 'label' => 'Latency', 'type' => 'text'],
                    ['key' => 'uptime', 'label' => 'Uptime', 'type' => 'text'],
                    ['key' => 'status', 'label' => 'Status', 'type' => 'text'],
                    ['key' => 'status_variant', 'label' => 'Status Style', 'type' => 'select', 'options' => [
                        ['label' => 'Active', 'value' => 'active'],
                        ['label' => 'Pending', 'value' => 'pending'],
                        ['label' => 'Draft', 'value' => 'draft'],
                    ]],
                ]],
                ['key' => 'metrics_label', 'label' => 'Metrics Label', 'type' => 'text'],
                ['key' => 'metrics', 'label' => 'Metrics', 'type' => 'repeater', 'fields' => [
                    ['key' => 'value', 'label' => 'Value', 'type' => 'text'],
                    ['key' => 'unit', 'label' => 'Unit', 'type' => 'text'],
                    ['key' => 'description', 'label' => 'Description', 'type' => 'textarea'],
                    ['key' => 'highlight', 'label' => 'Highlight Value', 'type' => 'boolean'],
                ]],
                ['key' => 'engine_tag', 'label' => 'Features Tag', 'type' => 'text'],
                ['key' => 'engine_title', 'label' => 'Features Title', 'type' => 'text'],
                ['key' => 'engine_cards', 'label' => 'Feature Cards', 'type' => 'repeater', 'fields' => [
                    ['key' => 'icon', 'label' => 'Icon', 'type' => 'select', 'options' => [
                        ['label' => 'Analytics', 'value' => 'analytics'],
                        ['label' => 'Pipeline', 'value' => 'pipeline'],
                        ['label' => 'Code', 'value' => 'code'],
                    ]],
                    ['key' => 'title', 'label' => 'Title', 'type' => 'text'],
                    ['key' => 'description', 'label' => 'Description', 'type' => 'textarea'],
                    ['key' => 'visual_type', 'label' => 'Visual Type', 'type' => 'select', 'options' => [
                        ['label' => 'Bars', 'value' => 'bars'],
                        ['label' => 'Pipeline', 'value' => 'pipeline'],
                        ['label' => 'Code', 'value' => 'code'],
                    ]],
                    ['key' => 'visual_primary', 'label' => 'Visual Primary Text', 'type' => 'text'],
                    ['key' => 'visual_secondary', 'label' => 'Visual Secondary Text', 'type' => 'text'],
                    ['key' => 'visual_tertiary', 'label' => 'Visual Tertiary Text', 'type' => 'text'],
                    ['key' => 'code_text', 'label' => 'Code Visual Text', 'type' => 'textarea'],
                ]],
                ['key' => 'pricing_tag', 'label' => 'Pricing Tag', 'type' => 'text'],
                ['key' => 'pricing_title', 'label' => 'Pricing Title', 'type' => 'text'],
                ['key' => 'monthly_label', 'label' => 'Monthly Toggle Label', 'type' => 'text'],
                ['key' => 'yearly_label', 'label' => 'Yearly Toggle Label', 'type' => 'text'],
                ['key' => 'yearly_save_label', 'label' => 'Yearly Savings Label', 'type' => 'text'],
                ['key' => 'pricing_plans', 'label' => 'Pricing Plans', 'type' => 'repeater', 'fields' => [
                    ['key' => 'name', 'label' => 'Name', 'type' => 'text'],
                    ['key' => 'description', 'label' => 'Description', 'type' => 'textarea'],
                    ['key' => 'currency', 'label' => 'Currency Symbol', 'type' => 'text'],
                    ['key' => 'monthly_price', 'label' => 'Monthly Price', 'type' => 'text'],
                    ['key' => 'yearly_price', 'label' => 'Yearly Price', 'type' => 'text'],
                    ['key' => 'period', 'label' => 'Period', 'type' => 'text'],
                    ['key' => 'monthly_billing', 'label' => 'Monthly Billing Text', 'type' => 'text'],
                    ['key' => 'yearly_billing', 'label' => 'Yearly Billing Text', 'type' => 'text'],
                    ['key' => 'button_label', 'label' => 'Button Label', 'type' => 'text'],
                    ['key' => 'button_url', 'label' => 'Button URL', 'type' => 'text'],
                    ['key' => 'featured', 'label' => 'Featured Plan', 'type' => 'boolean'],
                    ['key' => 'featured_label', 'label' => 'Featured Label', 'type' => 'text'],
                    ['key' => 'features', 'label' => 'Features', 'type' => 'textarea', 'description' => 'Enter one feature per line.'],
                ]],
                ['key' => 'faq_tag', 'label' => 'FAQ Tag', 'type' => 'text'],
                ['key' => 'faq_title', 'label' => 'FAQ Title', 'type' => 'text'],
                ['key' => 'faq_expand_label', 'label' => 'FAQ Expand Button Label', 'type' => 'text'],
                ['key' => 'faq_collapse_label', 'label' => 'FAQ Collapse Button Label', 'type' => 'text'],
                ['key' => 'faqs', 'label' => 'FAQ Items', 'type' => 'repeater', 'fields' => [
                    ['key' => 'question', 'label' => 'Question', 'type' => 'text'],
                    ['key' => 'answer', 'label' => 'Answer', 'type' => 'textarea'],
                ]],
                ['key' => 'primary_cta', 'label' => 'Lead Capture CTA', 'type' => 'cta', 'description' => 'Configure the lead capture form shown in the final CTA panel.'],
                ['key' => 'cta_tag', 'label' => 'CTA Tag', 'type' => 'text'],
                ['key' => 'cta_primary_label', 'label' => 'CTA Primary Button Label', 'type' => 'text'],
                ['key' => 'cta_primary_url', 'label' => 'CTA Primary Button URL', 'type' => 'text'],
                ['key' => 'cta_secondary_label', 'label' => 'CTA Secondary Button Label', 'type' => 'text'],
                ['key' => 'cta_secondary_url', 'label' => 'CTA Secondary Button URL', 'type' => 'text'],
                ['key' => 'footer_brand_description', 'label' => 'Footer Brand Description', 'type' => 'textarea'],
                ['key' => 'footer_columns', 'label' => 'Footer Columns', 'type' => 'repeater', 'fields' => [
                    ['key' => 'title', 'label' => 'Column Title', 'type' => 'text'],
                    ['key' => 'links', 'label' => 'Links', 'type' => 'textarea', 'description' => 'Enter links as Label|URL, one per line.'],
                ]],
                ['key' => 'footer_copy', 'label' => 'Footer Copyright Text', 'type' => 'text'],
                ['key' => 'footer_legal_links', 'label' => 'Footer Legal Links', 'type' => 'textarea', 'description' => 'Enter links as Label|URL, one per line.'],
            ],
            'default_content' => [
                'business_name'         => 'Catalyst',
                'nav_items'             => [
                    ['label' => 'Performance', 'url' => '#metrics'],
                    ['label' => 'Features', 'url' => '#engine'],
                    ['label' => 'Pricing', 'url' => '#pricing'],
                    ['label' => 'FAQ', 'url' => '#faq'],
                ],
                'login_label'          => 'Log In',
                'login_url'            => '#',
                'nav_cta_label'        => 'Start Free',
                'nav_cta_url'          => '#pricing',
                'hero_badge'           => 'v4.2 - Now with real-time sync',
                'hero_title'           => 'The analytics platform built for',
                'hero_accent_word'     => 'speed',
                'hero_subtitle'        => 'Stop waiting for insights. Catalyst delivers sub-second queries across billions of rows so your team ships decisions, not dashboards.',
                'hero_primary_label'   => 'Start Free Trial',
                'hero_primary_url'     => '#pricing',
                'hero_secondary_label' => 'Watch Demo',
                'hero_secondary_url'   => '#',
                'dashboard_tabs'       => [
                    ['label' => 'Overview', 'active' => true],
                    ['label' => 'Funnels', 'active' => false],
                    ['label' => 'Retention', 'active' => false],
                    ['label' => 'Revenue', 'active' => false],
                ],
                'dashboard_stats' => [
                    ['label' => 'Total Revenue', 'value' => '$2.4M', 'change' => '+18.2%', 'trend' => 'up'],
                    ['label' => 'Active Users', 'value' => '48,291', 'change' => '+7.4%', 'trend' => 'up'],
                    ['label' => 'Avg. Query Time', 'value' => '42ms', 'change' => '-23.5%', 'trend' => 'down'],
                ],
                'dashboard_table_title'   => 'Recent Pipelines',
                'dashboard_filter_label'  => 'All teams',
                'dashboard_name_header'   => 'Pipeline',
                'dashboard_events_header' => 'Events / hr',
                'dashboard_latency_header'=> 'Latency',
                'dashboard_uptime_header' => 'Uptime',
                'dashboard_status_header' => 'Status',
                'dashboard_rows'          => [
                    ['badge' => 'P1', 'name' => 'Checkout Funnel', 'events' => '1.2M', 'latency' => '34ms', 'uptime' => '99.98%', 'status' => 'Active', 'status_variant' => 'active'],
                    ['badge' => 'P2', 'name' => 'User Onboarding', 'events' => '847K', 'latency' => '52ms', 'uptime' => '99.91%', 'status' => 'Pending', 'status_variant' => 'pending'],
                    ['badge' => 'P3', 'name' => 'Revenue Tracker', 'events' => '2.1M', 'latency' => '28ms', 'uptime' => '99.99%', 'status' => 'Active', 'status_variant' => 'active'],
                    ['badge' => 'P4', 'name' => 'A/B Experiments', 'events' => '423K', 'latency' => '61ms', 'uptime' => '99.87%', 'status' => 'Draft', 'status_variant' => 'draft'],
                ],
                'metrics_label' => 'Performance that speaks for itself',
                'metrics'       => [
                    ['value' => '42', 'unit' => 'ms', 'description' => 'Average query response time across 10B+ row datasets', 'highlight' => true],
                    ['value' => '99.99', 'unit' => '%', 'description' => 'Guaranteed uptime SLA for all enterprise customers', 'highlight' => false],
                    ['value' => '10', 'unit' => 'x', 'description' => 'Faster than legacy warehouses at one-tenth the cost', 'highlight' => false],
                ],
                'engine_tag'   => 'The Engine',
                'engine_title' => 'Everything your data team actually needs',
                'engine_cards' => [
                    [
                        'icon'        => 'analytics',
                        'title'       => 'Real-Time Analytics',
                        'description' => 'Stream, transform, and visualize data the instant it arrives. No batching, no waiting, no stale dashboards.',
                        'visual_type' => 'bars',
                    ],
                    [
                        'icon'             => 'pipeline',
                        'title'            => 'Pipeline Orchestration',
                        'description'      => 'Build fault-tolerant data pipelines with visual drag-and-drop. Auto-retry and observability are built in.',
                        'visual_type'      => 'pipeline',
                        'visual_primary'   => 'Ingest',
                        'visual_secondary' => 'Transform',
                        'visual_tertiary'  => 'Deliver',
                    ],
                    [
                        'icon'        => 'code',
                        'title'       => 'SQL-First Interface',
                        'description' => 'Write standard SQL against any source. Auto-completion, version control, and collaborative editing come standard.',
                        'visual_type' => 'code',
                        'code_text'   => "SELECT user_id, COUNT(*)\nFROM events\nWHERE ts > '2026-01'\nGROUP BY 1",
                    ],
                ],
                'pricing_tag'       => 'Pricing',
                'pricing_title'     => 'Simple, transparent pricing',
                'monthly_label'     => 'Monthly',
                'yearly_label'      => 'Yearly',
                'yearly_save_label' => 'Save 25%',
                'pricing_plans'     => [
                    [
                        'name'            => 'Starter',
                        'description'     => 'For small teams getting started',
                        'currency'        => '$',
                        'monthly_price'   => '30',
                        'yearly_price'    => '22',
                        'period'          => 'per seat / month',
                        'monthly_billing' => 'Billed monthly',
                        'yearly_billing'  => '$264 billed annually',
                        'button_label'    => 'Get Started',
                        'button_url'      => '#',
                        'featured'        => false,
                        'featured_label'  => '',
                        'features'        => "Up to 5 team members\n1 billion events / month\n7-day data retention\nCommunity support",
                    ],
                    [
                        'name'            => 'Pro',
                        'description'     => 'For scaling data teams',
                        'currency'        => '$',
                        'monthly_price'   => '100',
                        'yearly_price'    => '75',
                        'period'          => 'per seat / month',
                        'monthly_billing' => 'Billed monthly',
                        'yearly_billing'  => '$900 billed annually',
                        'button_label'    => 'Get Started',
                        'button_url'      => '#',
                        'featured'        => true,
                        'featured_label'  => 'Most Popular',
                        'features'        => "Unlimited team members\n50 billion events / month\nUnlimited data retention\nPriority support + SLA\nSSO and audit logs",
                    ],
                    [
                        'name'            => 'Enterprise',
                        'description'     => 'For mission-critical deployments',
                        'currency'        => '$',
                        'monthly_price'   => '500',
                        'yearly_price'    => '375',
                        'period'          => 'starts from / month',
                        'monthly_billing' => 'Billed monthly',
                        'yearly_billing'  => '$4,500 billed annually',
                        'button_label'    => 'Contact Sales',
                        'button_url'      => '#',
                        'featured'        => false,
                        'featured_label'  => '',
                        'features'        => "Everything in Pro\nDedicated infrastructure\nCustom integrations\n24/7 dedicated support\n99.99% SLA guarantee",
                    ],
                ],
                'faq_tag'            => 'FAQ',
                'faq_title'          => 'Common questions, straight answers',
                'faq_expand_label'   => 'Expand All',
                'faq_collapse_label' => 'Collapse All',
                'faqs'               => [
                    ['question' => 'How long does the free trial last?', 'answer' => 'Every plan includes a 14-day free trial with full access to all features. No credit card required to get started.'],
                    ['question' => 'Can I switch plans later?', 'answer' => 'Yes. Upgrade or downgrade any time from your account settings. We prorate upgrades and apply remaining balance as credit.'],
                    ['question' => 'What data sources do you support?', 'answer' => 'Catalyst connects to PostgreSQL, MySQL, BigQuery, Snowflake, Redshift, S3, Kafka, and popular REST APIs.'],
                    ['question' => 'Is my data secure?', 'answer' => 'Data is encrypted at rest and in transit. Enterprise customers can use dedicated infrastructure and custom encryption keys.'],
                    ['question' => 'Do you offer onboarding support?', 'answer' => 'Pro customers get onboarding support for the first 30 days. Enterprise customers receive a dedicated solutions engineer.'],
                ],
                'primary_cta' => [
                    'type'            => 'demo_request',
                    'label'           => 'Demo request',
                    'title'           => 'Ready to accelerate your data?',
                    'description'     => 'Join 2,000+ teams shipping faster with sub-second analytics. Free for 14 days.',
                    'submit_label'    => 'Request demo',
                    'success_message' => 'Thanks. We will follow up with demo details soon.',
                    'fields'          => [
                        ['key' => 'name', 'label' => 'Name', 'type' => 'text', 'required' => true, 'placeholder' => 'Your name'],
                        ['key' => 'email', 'label' => 'Work email', 'type' => 'email', 'required' => true, 'placeholder' => 'you@company.com'],
                        ['key' => 'company', 'label' => 'Company', 'type' => 'text', 'required' => false, 'placeholder' => 'Company name'],
                    ],
                ],
                'cta_tag'                => 'Get started today',
                'cta_primary_label'      => 'Start Free Trial',
                'cta_primary_url'        => '#pricing',
                'cta_secondary_label'    => 'Talk to Sales',
                'cta_secondary_url'      => '#',
                'footer_brand_description' => 'The analytics platform built for speed. Sub-second queries, real-time pipelines, and infinite scale.',
                'footer_columns'         => [
                    ['title' => 'Resources', 'links' => "Documentation|#\nAPI Reference|#\nBlog|#\nChangelog|#\nStatus Page|#"],
                    ['title' => 'Support', 'links' => "Help Center|#\nCommunity Forum|#\nContact Us|#\nSystem Status|#"],
                    ['title' => 'Connect', 'links' => "Twitter / X|#\nGitHub|#\nLinkedIn|#\nYouTube|#"],
                ],
                'footer_copy'        => 'Copyright 2026 Catalyst Inc. All rights reserved. Design: TemplateMo',
                'footer_legal_links' => "Privacy|#\nTerms|#\nCookies|#",
            ],
        ];
    }
};
